// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtA2h-86AMv0Sf-psxGh5iUu_ihpygGyE',
    appId: '1:983591625578:web:7184e3b0a9fba201543b13',
    messagingSenderId: '983591625578',
    projectId: 'step-up-477ec',
    authDomain: 'step-up-477ec.firebaseapp.com',
    storageBucket: 'step-up-477ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5oz3kD7eNfOtJUGnSrmjd8TJYRSXBSI',
    appId: '1:983591625578:android:917009cb19b1fb55543b13',
    messagingSenderId: '983591625578',
    projectId: 'step-up-477ec',
    storageBucket: 'step-up-477ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBorUn2JuHdSgxvz_y4_leXs0Q5a-o_1og',
    appId: '1:983591625578:ios:506af45625c48c3e543b13',
    messagingSenderId: '983591625578',
    projectId: 'step-up-477ec',
    storageBucket: 'step-up-477ec.firebasestorage.app',
    iosClientId: '983591625578-1h42l0r5pb4becq5nvuda6irlm3d4dql.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBorUn2JuHdSgxvz_y4_leXs0Q5a-o_1og',
    appId: '1:983591625578:ios:506af45625c48c3e543b13',
    messagingSenderId: '983591625578',
    projectId: 'step-up-477ec',
    storageBucket: 'step-up-477ec.firebasestorage.app',
    iosClientId: '983591625578-1h42l0r5pb4becq5nvuda6irlm3d4dql.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtA2h-86AMv0Sf-psxGh5iUu_ihpygGyE',
    appId: '1:983591625578:web:4c633a294da35b9e543b13',
    messagingSenderId: '983591625578',
    projectId: 'step-up-477ec',
    authDomain: 'step-up-477ec.firebaseapp.com',
    storageBucket: 'step-up-477ec.firebasestorage.app',
  );
}
